### ISSUE TITLE
don't use git-lfs, use gh-actions build artifacts

### ISSUE THREAD

**Issue by dromer** [OwlPlug/central#5]
This way you can do reproducible and multi-target builds (x32/_64, arm32/64, win/osx/lin/etc.) and not push loads of changes into git-lfs that are not tied to any build config.

I believe gh-artifacts are also better cached so less bandwidth issues.

**Comment by DropSnorz** [comment]
Hello @dromer,

You are right, I'm not satisfied with how central works. Nothing is automated, it's hard to contribute and it rely on storage on my own external server. Plugins are downloaded from an external server (not hosted by github) that mirror this repo.

Using gh-actions artifacts, the pipeline must be run every 90 days to pull and store everything.

>By default, the artifacts and log files generated by workflows are retained for 90 days before they are automatically deleted. You can adjust the retention period, depending on the type of repository:
>
>    For public repositories: you can change this retention period to anywhere between 1 day or 90 days.

I'm looking for a smooth way to handle plugin submission and hosting. There is interresting solution on [winget](https://github.com/microsoft/winget-pkgs) and [hombrew cask](https://github.com/Homebrew/homebrew-cask) side.

**Comment by dromer** [comment]
Why does the pipeline have to be run every 90 days? GH-Artifact retention?

Maybe simply using release builds makes more sense then? afaik those are persistent

**Comment by DropSnorz** [comment]
Hi !

This issue has been resolved. I've created a new repository, [owlplug-registry](https://github.com/OwlPlug/owlplug-registry), to store plugin manifests. Plugin submission should be easier and artifact storage is no longer supported by git lfs 🙂 

The new registry will be the default source for the next OwlPlug versions. 
I'will archive this repository soon.

**Comment by dromer** [comment]
Wait what, you are now pushing zips with binaries straight into git?

Expect your repo to grow exponentially ..
